"""esquema inicial

Revision ID: 0bb3da1e29b1
Revises: 
Create Date: 2026-09-30 15:27:54.536020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bb3da1e29b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_fetch_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_fetch_log', schema=None) as batch_op:
        batch_op.create_index('ix_fetch_time', [sa.literal_column('fetched_at DESC')], unique=False)

    op.create_table('scoring_parameters',
    sa.Column('version', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tolerances', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rain_prob_threshold_pct', sa.SmallInteger(), nullable=False),
    sa.Column('rain_observed_threshold_mm', sa.Numeric(precision=3, scale=1, asdecimal=False), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    with op.batch_alter_table('scoring_parameters', schema=None) as batch_op:
        batch_op.create_index('ux_scoring_single_active', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))

    op.create_table('weather_forecasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_code', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1, asdecimal=False), nullable=False),
    sa.Column('feels_like_c', sa.Numeric(precision=4, scale=1, asdecimal=False), nullable=True),
    sa.Column('humidity_pct', sa.SmallInteger(), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=5, scale=2, asdecimal=False), server_default='0', nullable=False),
    sa.Column('rain_probability_pct', sa.SmallInteger(), nullable=True),
    sa.Column('wind_kph', sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=True),
    sa.Column('cloud_cover_pct', sa.SmallInteger(), nullable=True),
    sa.Column('weather_code', sa.SmallInteger(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.CheckConstraint('cloud_cover_pct BETWEEN 0 AND 100', name='ck_fc_cloud'),
    sa.CheckConstraint('humidity_pct BETWEEN 0 AND 100', name='ck_fc_humidity'),
    sa.CheckConstraint('precipitation_mm >= 0', name='ck_fc_precip'),
    sa.CheckConstraint('rain_probability_pct BETWEEN 0 AND 100', name='ck_fc_rain_prob'),
    sa.CheckConstraint('wind_kph >= 0', name='ck_fc_wind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_code', 'issued_at', 'target_at', name='uq_forecast_issue_target')
    )
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_fc_target', ['location_code', 'target_at', sa.literal_column('issued_at DESC')], unique=False)

    op.create_table('forecast_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', sa.BigInteger(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=True),
    sa.Column('params_version', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2, asdecimal=False), nullable=False),
    sa.Column('accuracy_label', sa.String(length=40), nullable=False),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('accuracy_score BETWEEN 0 AND 100', name='ck_eval_score'),
    sa.ForeignKeyConstraint(['forecast_id'], ['weather_forecasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['params_version'], ['scoring_parameters.version'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_id', 'params_version', name='uq_eval_forecast_params')
    )
    with op.batch_alter_table('forecast_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_evaluations_forecast_id'), ['forecast_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecast_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecast_evaluations_forecast_id'))

    op.drop_table('forecast_evaluations')
    with op.batch_alter_table('weather_forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_fc_target')

    op.drop_table('weather_forecasts')
    with op.batch_alter_table('scoring_parameters', schema=None) as batch_op:
        batch_op.drop_index('ux_scoring_single_active', postgresql_where=sa.text('is_active'))

    op.drop_table('scoring_parameters')
    with op.batch_alter_table('provider_fetch_log', schema=None) as batch_op:
        batch_op.drop_index('ix_fetch_time')

    op.drop_table('provider_fetch_log')
    # ### end Alembic commands ###
