"""esquema inicial

Revision ID: 0b4cda61887d
Revises: 
Create Date: 2026-09-30 15:27:51.170997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4cda61887d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_fetch_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('current','hourly')", name='ck_fetch_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_fetch_log', schema=None) as batch_op:
        batch_op.create_index('ix_fetch_kind_time', ['kind', sa.literal_column('fetched_at DESC')], unique=False)

    op.create_table('weather_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_code', sa.String(length=30), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Numeric(precision=4, scale=1, asdecimal=False), nullable=False),
    sa.Column('feels_like_c', sa.Numeric(precision=4, scale=1, asdecimal=False), nullable=True),
    sa.Column('humidity_pct', sa.SmallInteger(), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(precision=5, scale=2, asdecimal=False), server_default='0', nullable=False),
    sa.Column('rain_probability_pct', sa.SmallInteger(), nullable=True),
    sa.Column('wind_kph', sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=True),
    sa.Column('cloud_cover_pct', sa.SmallInteger(), nullable=True),
    sa.Column('weather_code', sa.SmallInteger(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('is_day', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('current','hourly')", name='ck_obs_source'),
    sa.CheckConstraint('cloud_cover_pct BETWEEN 0 AND 100', name='ck_obs_cloud'),
    sa.CheckConstraint('humidity_pct BETWEEN 0 AND 100', name='ck_obs_humidity'),
    sa.CheckConstraint('precipitation_mm >= 0', name='ck_obs_precip'),
    sa.CheckConstraint('rain_probability_pct BETWEEN 0 AND 100', name='ck_obs_rain_prob'),
    sa.CheckConstraint('wind_kph >= 0', name='ck_obs_wind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_code', 'observed_at', 'source', name='uq_obs_location_time_source')
    )
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_location_time', ['location_code', sa.literal_column('observed_at DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_location_time')

    op.drop_table('weather_observations')
    with op.batch_alter_table('provider_fetch_log', schema=None) as batch_op:
        batch_op.drop_index('ix_fetch_kind_time')

    op.drop_table('provider_fetch_log')
    # ### end Alembic commands ###
