"""esquema inicial del catalogo

Revision ID: 71d9d7eff8cd
Revises: 
Create Date: 2026-09-30 16:32:19.687216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71d9d7eff8cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('hike_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('depth_label', sa.String(length=40), nullable=True),
    sa.Column('depth_min_m', sa.Numeric(precision=3, scale=1, asdecimal=False), nullable=True),
    sa.Column('depth_max_m', sa.Numeric(precision=3, scale=1, asdecimal=False), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='draft', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy','moderate','hard')", name='ck_places_difficulty'),
    sa.CheckConstraint("status IN ('draft','published','archived')", name='ck_places_status'),
    sa.CheckConstraint('depth_min_m IS NULL OR depth_max_m IS NULL OR depth_min_m <= depth_max_m', name='ck_places_depth_order'),
    sa.CheckConstraint('hike_minutes > 0', name='ck_places_hike'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index('ix_places_public', ['sort_order', 'name'], unique=False, postgresql_where=sa.text("status = 'published'"))

    op.create_table('place_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('place_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_audit_place_id'), ['place_id'], unique=False)

    op.create_table('place_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes_full', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('place_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_photos_place_id'), ['place_id'], unique=False)
        batch_op.create_index('ux_place_single_cover', ['place_id'], unique=True, postgresql_where=sa.text('is_cover'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_photos', schema=None) as batch_op:
        batch_op.drop_index('ux_place_single_cover', postgresql_where=sa.text('is_cover'))
        batch_op.drop_index(batch_op.f('ix_place_photos_place_id'))

    op.drop_table('place_photos')
    with op.batch_alter_table('place_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_audit_place_id'))

    op.drop_table('place_audit')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index('ix_places_public', postgresql_where=sa.text("status = 'published'"))

    op.drop_table('places')
    # ### end Alembic commands ###
